# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/v1/calculator.proto',
  package='api.v1',
  syntax='proto3',
  serialized_options=b'Z\tgo/api/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61pi/v1/calculator.proto\x12\x06\x61pi.v1\"8\n\x0e\x43omputeRequest\x12\x12\n\x04num1\x18\x01 \x01(\x02R\x04num1\x12\x12\n\x04num2\x18\x02 \x01(\x02R\x04num2\")\n\x0f\x43omputeResponse\x12\x16\n\x06result\x18\x01 \x01(\x02R\x06result2\xf3\x01\n\x11\x43\x61lculatorService\x12\x36\n\x03Sum\x12\x16.api.v1.ComputeRequest\x1a\x17.api.v1.ComputeResponse\x12\x36\n\x03Sub\x12\x16.api.v1.ComputeRequest\x1a\x17.api.v1.ComputeResponse\x12\x36\n\x03\x44iv\x12\x16.api.v1.ComputeRequest\x1a\x17.api.v1.ComputeResponse\x12\x36\n\x03Mul\x12\x16.api.v1.ComputeRequest\x1a\x17.api.v1.ComputeResponseB\x0bZ\tgo/api/v1b\x06proto3'
)




_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='api.v1.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='api.v1.ComputeRequest.num1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='num1', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num2', full_name='api.v1.ComputeRequest.num2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='num2', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=91,
)


_COMPUTERESPONSE = _descriptor.Descriptor(
  name='ComputeResponse',
  full_name='api.v1.ComputeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='api.v1.ComputeResponse.result', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='result', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeResponse'] = _COMPUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEREQUEST,
  '__module__' : 'api.v1.calculator_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.ComputeRequest)
  })
_sym_db.RegisterMessage(ComputeRequest)

ComputeResponse = _reflection.GeneratedProtocolMessageType('ComputeResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERESPONSE,
  '__module__' : 'api.v1.calculator_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.ComputeResponse)
  })
_sym_db.RegisterMessage(ComputeResponse)


DESCRIPTOR._options = None

_CALCULATORSERVICE = _descriptor.ServiceDescriptor(
  name='CalculatorService',
  full_name='api.v1.CalculatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=137,
  serialized_end=380,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='api.v1.CalculatorService.Sum',
    index=0,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Sub',
    full_name='api.v1.CalculatorService.Sub',
    index=1,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Div',
    full_name='api.v1.CalculatorService.Div',
    index=2,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Mul',
    full_name='api.v1.CalculatorService.Mul',
    index=3,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATORSERVICE)

DESCRIPTOR.services_by_name['CalculatorService'] = _CALCULATORSERVICE

# @@protoc_insertion_point(module_scope)
