# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import calculator_pb2 as api_dot_v1_dot_calculator__pb2


class CalculatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sum = channel.unary_unary(
                '/api.v1.CalculatorService/Sum',
                request_serializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
                )
        self.Sub = channel.unary_unary(
                '/api.v1.CalculatorService/Sub',
                request_serializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
                )
        self.Div = channel.unary_unary(
                '/api.v1.CalculatorService/Div',
                request_serializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
                )
        self.Mul = channel.unary_unary(
                '/api.v1.CalculatorService/Mul',
                request_serializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
                )


class CalculatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sum(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sub(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Div(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mul(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sum': grpc.unary_unary_rpc_method_handler(
                    servicer.Sum,
                    request_deserializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.FromString,
                    response_serializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.SerializeToString,
            ),
            'Sub': grpc.unary_unary_rpc_method_handler(
                    servicer.Sub,
                    request_deserializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.FromString,
                    response_serializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.SerializeToString,
            ),
            'Div': grpc.unary_unary_rpc_method_handler(
                    servicer.Div,
                    request_deserializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.FromString,
                    response_serializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.SerializeToString,
            ),
            'Mul': grpc.unary_unary_rpc_method_handler(
                    servicer.Mul,
                    request_deserializer=api_dot_v1_dot_calculator__pb2.ComputeRequest.FromString,
                    response_serializer=api_dot_v1_dot_calculator__pb2.ComputeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.CalculatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.CalculatorService/Sum',
            api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
            api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.CalculatorService/Sub',
            api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
            api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Div(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.CalculatorService/Div',
            api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
            api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Mul(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.CalculatorService/Mul',
            api_dot_v1_dot_calculator__pb2.ComputeRequest.SerializeToString,
            api_dot_v1_dot_calculator__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
