# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/greet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/v1/greet.proto',
  package='api.v1',
  syntax='proto3',
  serialized_options=b'Z\tgo/api/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x61pi/v1/greet.proto\x12\x06\x61pi.v1\">\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n\x08greeting\x18\x02 \x01(\tR\x08greeting\")\n\rHelloResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"X\n\x0c\x44\x65layedReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12.\n\x07request\x18\x02 \x03(\x0b\x32\x14.api.v1.HelloRequestR\x07request2\x97\x02\n\x0eGreeterService\x12\x37\n\x08SayHello\x12\x14.api.v1.HelloRequest\x1a\x15.api.v1.HelloResponse\x12@\n\x0fParrotSaysHello\x12\x14.api.v1.HelloRequest\x1a\x15.api.v1.HelloResponse0\x01\x12\x45\n\x15\x43hattyClientSaysHello\x12\x14.api.v1.HelloRequest\x1a\x14.api.v1.DelayedReply(\x01\x12\x43\n\x10InteractingHello\x12\x14.api.v1.HelloRequest\x1a\x15.api.v1.HelloResponse(\x01\x30\x01\x42\x0bZ\tgo/api/v1b\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='api.v1.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='api.v1.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='greeting', full_name='api.v1.HelloRequest.greeting', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='greeting', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=92,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='api.v1.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='api.v1.HelloResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='message', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=135,
)


_DELAYEDREPLY = _descriptor.Descriptor(
  name='DelayedReply',
  full_name='api.v1.DelayedReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='api.v1.DelayedReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='message', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='api.v1.DelayedReply.request', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='request', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=225,
)

_DELAYEDREPLY.fields_by_name['request'].message_type = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.message_types_by_name['DelayedReply'] = _DELAYEDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'api.v1.greet_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'api.v1.greet_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

DelayedReply = _reflection.GeneratedProtocolMessageType('DelayedReply', (_message.Message,), {
  'DESCRIPTOR' : _DELAYEDREPLY,
  '__module__' : 'api.v1.greet_pb2'
  # @@protoc_insertion_point(class_scope:api.v1.DelayedReply)
  })
_sym_db.RegisterMessage(DelayedReply)


DESCRIPTOR._options = None

_GREETERSERVICE = _descriptor.ServiceDescriptor(
  name='GreeterService',
  full_name='api.v1.GreeterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=228,
  serialized_end=507,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='api.v1.GreeterService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ParrotSaysHello',
    full_name='api.v1.GreeterService.ParrotSaysHello',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ChattyClientSaysHello',
    full_name='api.v1.GreeterService.ChattyClientSaysHello',
    index=2,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_DELAYEDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InteractingHello',
    full_name='api.v1.GreeterService.InteractingHello',
    index=3,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETERSERVICE)

DESCRIPTOR.services_by_name['GreeterService'] = _GREETERSERVICE

# @@protoc_insertion_point(module_scope)
