# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import greet_pb2 as api_dot_v1_dot_greet__pb2


class GreeterServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/api.v1.GreeterService/SayHello',
                request_serializer=api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_greet__pb2.HelloResponse.FromString,
                )
        self.ParrotSaysHello = channel.unary_stream(
                '/api.v1.GreeterService/ParrotSaysHello',
                request_serializer=api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_greet__pb2.HelloResponse.FromString,
                )
        self.ChattyClientSaysHello = channel.stream_unary(
                '/api.v1.GreeterService/ChattyClientSaysHello',
                request_serializer=api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_greet__pb2.DelayedReply.FromString,
                )
        self.InteractingHello = channel.stream_stream(
                '/api.v1.GreeterService/InteractingHello',
                request_serializer=api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_greet__pb2.HelloResponse.FromString,
                )


class GreeterServiceServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParrotSaysHello(self, request, context):
        """Server Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChattyClientSaysHello(self, request_iterator, context):
        """Client Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InteractingHello(self, request_iterator, context):
        """Both Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=api_dot_v1_dot_greet__pb2.HelloRequest.FromString,
                    response_serializer=api_dot_v1_dot_greet__pb2.HelloResponse.SerializeToString,
            ),
            'ParrotSaysHello': grpc.unary_stream_rpc_method_handler(
                    servicer.ParrotSaysHello,
                    request_deserializer=api_dot_v1_dot_greet__pb2.HelloRequest.FromString,
                    response_serializer=api_dot_v1_dot_greet__pb2.HelloResponse.SerializeToString,
            ),
            'ChattyClientSaysHello': grpc.stream_unary_rpc_method_handler(
                    servicer.ChattyClientSaysHello,
                    request_deserializer=api_dot_v1_dot_greet__pb2.HelloRequest.FromString,
                    response_serializer=api_dot_v1_dot_greet__pb2.DelayedReply.SerializeToString,
            ),
            'InteractingHello': grpc.stream_stream_rpc_method_handler(
                    servicer.InteractingHello,
                    request_deserializer=api_dot_v1_dot_greet__pb2.HelloRequest.FromString,
                    response_serializer=api_dot_v1_dot_greet__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.GreeterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GreeterService(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.GreeterService/SayHello',
            api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
            api_dot_v1_dot_greet__pb2.HelloResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParrotSaysHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/api.v1.GreeterService/ParrotSaysHello',
            api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
            api_dot_v1_dot_greet__pb2.HelloResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChattyClientSaysHello(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/api.v1.GreeterService/ChattyClientSaysHello',
            api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
            api_dot_v1_dot_greet__pb2.DelayedReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InteractingHello(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/api.v1.GreeterService/InteractingHello',
            api_dot_v1_dot_greet__pb2.HelloRequest.SerializeToString,
            api_dot_v1_dot_greet__pb2.HelloResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
